/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Animals": "动物",
    "Barns": "谷仓",
    "Click to view status": "点击查看统计",
    "Cultura": "文化",
    "Discord": "Discord",
    "Donate": "捐赠",
    "Email": "Email",
    "FAQs": "常见问题",
    "Horse": "马",
    "Incubator": "孵化器",
    "Locked": "未解锁",
    "Menu": "菜单",
    "Patreon": "帕特伦",
    "Races": "赛车",
    "Reddit": "Reddit",
    "Relay Teams": "接力队",
    "Resources": "资源",
    "Shop": "商店",
    "Stats": "统计",
    "Tip: After upgrading training options, reselect them to gain their benefits!": "提示：升级培训选项后，重新选择它们以获得它们的好处！",
    "Back": "返回",
    "Buy": "购买",
    "Purchase Barn": "购买谷仓",
    "Tip: Don't forget to export your save regularly!": "提示：不要忘记定期导出您的存档！",
    "Tip: Can't quite finish a close race? Burst Chance and Distance are not affected by Diminishing Returns, so continue to increase those stats to get ahead!": "提示：无法完成一场势均力敌的比赛？ 爆发机会和距离不受收益递减的影响，因此请继续增加这些统计数据以取得成功！",
    "Build": "建造",
    "Change Training": "改变训练",
    "Click an option below to start training.": "单击下面的选项开始训练。",
    "Coach": "教练",
    "Large": "大",
    "Medium": "中",
    "No Training Assigned": "未指定训练",
    "Reset Filters": "重置过滤器",
    "Short Track Running": "短道跑步",
    "Small": "小",
    "Sprints": "冲刺",
    "Swap": "交换",
    "Tip: Want to take a more hands on approach? Go to any barn that has an animal assigned and start coaching to raise stats manually!": "提示：想要更多地亲身体验吗？ 前往任何分配了动物的谷仓并开始指导手动提高统计数据！",
    "Trail Running": "越野跑",
    "Upgrade": "升级",
    "Unassign": "取消分配",
    " your stat boost will be increased significantly and you will increase your Chain Modifier by an amount proportional to how fast you completed the scrimmage. Your Chain Modifier is a multiplier for each subsequent stat gain during this set of scrimmages. Increasing your Chain Modifier quickly is key to getting big stat boosts!": "您的统计数据提升将显着增加，并且您的链修改器将增加与您完成混战的速度成正比的数量。 在这组混战期间，您的链修正值是每个后续统计增益的乘数。 快速增加你的链修改器是获得大数据提升的关键！",
    "Each animal can only scrimmage a certain amount at a time. By default, you have 15 energy. After completing Circuit Rank A, you gain 15 more for a total of 30. After starting a round of scrimmage races, a 15 minute timer starts. Until that timer ends, a new round of scrimmages cannot be started for that animal.": "每只动物一次只能混战一定数量。 默认情况下，你有 15 能量。 完成巡回赛 A 级后，您可以获得 15 分，总共 30 分。开始一轮混战后，15 分钟计时器开始计时。 在该计时器结束之前，该动物无法开始新一轮的混战。",
    ". Complete scrimmages so that your animal can get back in the race faster after Breeding!": ".完成混战，让您的动物在育种后更快地回到比赛中！",
    "As your racer runs, they will need the extra motivation only a coach can provide to succeed. Select the right option under the race drawing to help your animal stay on track.": "当您的赛车手跑步时，他们将需要只有教练才能提供的额外动力才能取得成功。在比赛图纸下选择正确的选项，以帮助您的动物保持在轨道上。",
    "Blow": "吹",
    "BURST!": "爆裂！",
    "BURSTS!": "爆发！",
    "BURSTS!\nFinished the scrimmage in 1.85 seconds and raised the default value of its base Focus by 0.246.": "BURSTS！\n在 1.85 秒内完成了混战，并将其基础焦点的默认值提高了 0.246。",
    "Chain Modifier:": "链修改器：",
    "Choosing the right option fast enough may trigger your animal to Burst.": "足够快地选择正确的选项可能会触发您的动物爆发。",
    "Coaching": "辅导",
    "Continue": "继续",
    "Cost to build larger barn: \n4000 Coins \n\nYou will be able to do Large trainings and increase idle training time to 12 hours.": "建造更大谷仓的成本：\n4000 金币 \n\n您将能够进行大型训练并将空闲训练时间增加到 12 小时。",
    "Cost to build larger barn: \n500 Coins \n\nYou will be able to do Medium trainings and increase idle training time to 8 hours.": "建造更大谷仓的成本：\n500 金币 \n\n您将能够进行中等训练并将空闲训练时间增加到 8 小时。",
    "Current Status:": "当前状态：",
    "During a scrimmage, your racer will race against the clock to complete paths in a certain amount of time. The faster they go, the better the rewards. At the end of each scrimmage run, your racer will be rewarded with": "在混战期间，您的赛车手将争分夺秒地在一定时间内完成路径。他们走得越快，奖励就越好。在每次混战结束时，您的赛车手将获得奖励",
    "END": "结尾",
    "Help your partner race as fast as possible. Successfully making it through will reward your partner with a permanent boost to their default base stat value after Breeding.": "帮助您的搭档尽快比赛。成功通过将奖励您的伴侣，使其在育种后的默认基础统计值永久提升。",
    "histle": "嘶嘶声",
    "Horse Current Stats:\nSpeed: 5,000\nAcceleration: 5,000\nEndurance: 5,000\nPower: 5,000\nFocus: 5,000\nAdaptability: 5,000\nDiminishing Returns: 5020": "马当前统计：\n速度：5,000\n加速度：5,000\n耐力：5,000\n力量：5,000\n专注：5,000\n适应性：5,000\n递减回报：5020",
    "If you complete your scrimmage in 4 seconds or less": "如果您在 4 秒或更短的时间内完成混战",
    "is off to a slow start, not really caring how well they do.": "起步缓慢，并不真正关心他们的表现。",
    "is off to a slow start, not really caring how well they do.\nFinished the scrimmage in 12.00 seconds and raised the default value of its base Focus by 0.014.": "开局很慢，并不真正关心他们的表现。\n在 12.00 秒内完成了混战，并将其基础焦点的默认值提高了 0.014。",
    "is off to a slow start, not really caring how well they do.\nFinished the scrimmage in 12.09 seconds and raised the default value of its base Focus by 0.014.": "开局很慢，并不真正关心他们的表现。\n在 12.09 秒内完成了混战，并将其基础焦点的默认值提高了 0.014。",
    "is off to a slow start, not really caring how well they do.\nYou hold a treat at the end of the finish line, giving": "起步很慢，并不真正关心他们的表现。\n你在终点线的尽头拿着一个款待，给",
    "looks like they are losing control and may stumble!": "看起来他们正在失去控制，可能会绊倒！",
    "loses focus!": "失去焦点！",
    "loses focus!\nFinished the scrimmage in 4.33 seconds and raised the default value of its base Speed by 0.037.": "失去焦点！\n在 4.33 秒内完成了混战，并将其基本速度的默认值提高了 0.037。",
    "loses focus!\nFinished the scrimmage in 7.72 seconds and raised the default value of its base Acceleration by 0.014.": "失去焦点！\n在 7.72 秒内完成了混战，并将其基础加速度的默认值提高了 0.014。",
    "loses focus!\nFinished the scrimmage in 7.72 seconds and raised the default value of its base Endurance by 0.014.": "失去焦点！\n在 7.72 秒内完成了混战，并将其基础耐力的默认值提高了 0.014。",
    "loses focus!\nFinished the scrimmage in 7.72 seconds and raised the default value of its base Focus by 0.014.": "失去焦点！\n在 7.72 秒内完成了混战，并将其基础焦点的默认值提高了 0.014。",
    "Lost Focus": "失去焦点",
    "Low Drive": "低驱动",
    "ncouragement": "鼓励",
    "No Barns Available": "没有可用的谷仓",
    "OK": "好的",
    "ood": "好东西",
    "out for some scrimmage races.": "参加一些混战比赛。",
    "out into an open area for practice.": "到一个空旷的地方练习。",
    "Pause": "暂停",
    "permanent stat boosts that increase the base value of a stat after Breeding": "永久统计提升，在育种后增加统计的基础值",
    "PWR": "力量",
    "Scrimmage": "混战",
    "Scrimmage Energy:": "混战能量：",
    "Scrimmage Info": "混战信息",
    "Shout": "喊",
    "Show": "节目",
    "Show your animals the way by tracing each path. Successfully making it through will reward your partner with a stat point.": "通过追踪每条路径向您的动物展示方式。成功通过会奖励你的伙伴一个统计点。",
    "SPD": "速度",
    "Stumbled": "跌跌撞撞",
    "stumbled!": "跌跌撞撞！",
    "stumbled!\nFinished the scrimmage in 8.00 seconds and raised the default value of its base Adaptability by 0.014.": "绊倒了！\n在 8.00 秒内完成了混战，并将其基础适应性的默认值提高了 0.014。",
    "stumbled!\nFinished the scrimmage in 8.00 seconds and raised the default value of its base Endurance by 0.014.": "绊倒了！\n在 8.00 秒内完成了混战，并将其基础耐力的默认值提高了 0.014。",
    "stumbled!\nFinished the scrimmage in 8.00 seconds and raised the default value of its base Power by 0.014.": "绊倒了！\n在 8.00 秒内完成了混战，并将其基础力量的默认值提高了 0.014。",
    "Stumbling": "跌跌撞撞",
    "Swap Animals": "交换动物",
    "the inspiration to continue.": "继续的灵感。",
    "Tip: Each animal gains more or less racing stats from a base stat than other animals. Hover over each base stat in the Animals tab to see its modifier.": "提示：与其他动物相比，每只动物从基本统计数据中获得的赛跑统计数据或多或少。将鼠标悬停在“动物”选项卡中的每个基本属性上以查看其修饰符。",
    "Tip: Small barns allow training for 4 hours, medium for 8 hours, and large for 12 hours. Your animals will train even when the game is not active.": "提示：小型谷仓允许训练 4 小时，中型谷仓 8 小时，大型谷仓 12 小时。即使游戏不活跃，您的动物也会训练。",
    "With": "和",
    "You bring": "你带了",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Coins:": "金币：",
    "Medals:": "奖牌：",
    "Small Barn ": "小谷仓",
    "Total Breeds: ": "总品种：",
    "Total Meters Covered: ": "总米数：",
    "Barn Level ": "谷仓等级 ",
    "(Retry in ": "(重试于 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^x ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Small \- (.+) sec$/, '小 \- $1 秒'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Coins$/, '$1 金币'],
    [/^\+([\d\.]+) Acceleration$/, '$1 加速'],
    [/^\+([\d\.]+) Speed$/, '$1 速度'],
    [/^\+([\d\.]+) Speed\n\+([\d\.]+) Endurance$/, '$1 速度\n\+$2 耐力'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);